name: Generate Snake Game

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate snake game
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: dist/github-snake.gif

      - name: Commit and Push
        run: |
          git config --local user.email "a.boeckmann23@gmail.com"
          git config --local user.name "Shcoobz"
          git add dist/github-snake.svg
          git commit -m "Update GitHub snake animation" -a || echo "No changes to commit"
          git push
