name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
           SECTION_NAME: waka
            SHOW_OS: True
            SHOW_PROJECTS: True
            SHOW_EDITORS: True
            SHOW_TIMEZONE: False
            SHOW_COMMIT: True
            SHOW_LANGUAGE: True
            SHOW_LINES_OF_CODE: False
            SHOW_LANGUAGE_PER_REPO: True
            SHOW_LOC_CHART: False 
            SHOW_DAYS_OF_WEEK: True
            SHOW_PROFILE_VIEWS: True
            SHOW_SHORT_INFO: True
            SHOW_UPDATED_DATE: True # flag can be set to True to show updated date in end of paragraph
            SHOW_TOTAL_CODE_TIME: False 
            COMMIT_BY_ME: False # flag can be set to True to commit the code using your name and email
            COMMIT_MESSAGE: Updated with Dev Metrics
            COMMIT_USERNAME: readme-bot # flag can be set to username to commit the code, default is "readme-bot"
            # COMMIT_EMAIL flag can be set to email to commit the code, default is "41898282+github-actions[bot]@users.noreply.github.com"
            COMMIT_SINGLE: False
            LOCALE: en
            UPDATED_DATE_FORMAT: %d/%m/%Y %H:%M:%S
            SYMBOL_VERSION: 3
            
            
            IGNORED_REPOS: "repo1, repo2, repo3"
