name: Waka Readme

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TIMEZONE: False
          SHOW_LINES_OF_CODE: False
          SHOW_LOC_CHART: False
          SHOW_TOTAL_CODE_TIME: False
          COMMIT_BY_ME: False
          COMMIT_MESSAGE: Updated with Dev Metrics
          COMMIT_SINGLE: False
          LOCALE: en
          UPDATED_DATE_FORMAT: %d/%m/%Y %H:%M:%S
          SYMBOL_VERSION: 3
          IGNORED_REPOS: 'Shcoobz, list_projects, list_basicJS-projects, list_basicJS-and-advancedJS-projects, list_basicJS-and-advancedJS-plus-projects, list_mern-projects, list_basicJava-projects'
